### ISSUE TITLE
VPSM and VP fork

### ISSUE THREAD

**Issue by tebowy** [hythloday/VenturePlanSoDMissions#18]
I have the forked VP that was provisionally available on GitHub (not by foxlift) which happens to have some 9.1 abilities added (from the reports they've gathered). Is this addon compatible with that fork, or should I revert to the latest upstream?

**Comment by epiktetov** [comment]
Likely compatible, but to tell for sure it would be helpful if you provide a link to "that fork" ;)

**Comment by tebowy** [comment]
https://archive.org/details/github.com-Gaboros-VenturePlan_-_2021-07-10_22-50-32

**Comment by hythloday** [comment]
I can't have links to infringing links on this repo, c'mon.

**Comment by hythloday** [comment]
If you have additional 9.1 abilities, they'll be in the vs-spells.lua file in the addon. What you'll need to do is to compare them, by number, with the abilities in the extra-vs-spells.lua file in this repo. If you find something that differs, please open an issue or a PR with the change in it. I'm not going to look through the fork myself because they tend to breach the author's copyright and obviously I can't be a party to that.

**Comment by hythloday** [comment]
To answer your direct question, this addon will be compatible with a fork, but will overwrite the data in the fork with its own data where they conflict. The solution to get both is the one I outlined above.

Going to close this but look forward to an issue/PR from you with the data if you find anything differs. :)
