### ISSUE TITLE
"Shirking Work" mission failed

### ISSUE THREAD

**Issue by sgubbins** [hythloday/VenturePlanSoDMissions#29]
https://www.wowhead.com/mission=2300/shirking-work

https://www.wowhead.com/adventure-combatant-ability/shiftless-smash-326
"Shiftless Smash" 326
Deals $s1 Frost damage to all adjacent enemies.

**Comment by LostTemple1990** [comment]
there may be something wrong with target type "cleave" in sim
but I don't have enough logs to check out the rule of type "cleave"
you can check my personal issue for this spell
[https://github.com/LostTemple1990/Issues-of-self-debugged-VenturePlan/issues/3](url)
To fix this,it needs to modify the source code of the original addon.
**But**, this bug would not cause mission fail because it dealt less damage in real log than in sim
It's better to provide a **log** of your failure mission to help check what's wrong with it

**Comment by hythloday** [comment]
Thanks for this too - closing with the same rationale.

I'm considering replacing the sim part so I can modify it to fix issues such as the cleave. If/when I do then I'll be able to track this better.
