### ISSUE TITLE
Mission "Piratical Problems" failed

### ISSUE THREAD

**Issue by xinye83** [hythloday/VenturePlanSoDMissions#45]
Logs generated with suggestions in #43: [piratical_problems_logs.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7102916/piratical_problems_logs.txt)

Mission info dump from _another character_: [piratical_problems_dump.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7102944/piratical_problems_dump.txt)

**Comment by TruthNZ** [comment]
Ok, I'm guessing a bit at the code here, but it looks like it should be 2 effects instead of the existing one:
```
[337]={
	{type="nuke", target=1, damageATK=200},
	{type="aura", target=1, duration=4, damageATK=40, noFirstTick=true}, 
}, --Wavebender's Tide
```

**Comment by xinye83** [comment]
This is what I would do but I'm also guessing the code a little bit. I will test this the next time I see the mission.

**Comment by zealvurte** [comment]
It being 1 or 2 effects won't make a difference in this case.

**Comment by zealvurte** [comment]
The Corsair Cannoneers are auto-attack `spellID` `15`  instead of `11` in the sim, due to their `role` being `2` (Ranged (Physical)). They would need entries in `overrideAA` for `missionID` `2307` with `slot` `9` and `12`.

The Corsair Wavebenders are auto-attack `spellID` `15` instead of `11` in the sim, due to their `role` being `3` (Ranged (Magic)). They would need entries in `overrideAA` for `missionID` `2307` with `slot` `10` and `11`.

**Comment by TruthNZ** [comment]
Hmm, seemed to work for me doing what I had above. At least for this mission (I'm still failing others listed in the issues however).

I'm unsure how you change the overrideAA. I can see the code in vs.lua where it's assigned (line 131 in mine), but I don't understand the format of the field.

**Comment by zealvurte** [comment]
For encounters, the key format is `4+2*slot+32*missionID`

**Comment by Divergentcurl** [comment]
Using the above formula I added `[73846]=0, [73848]=0, [73850]=0, [73852]=0` to overrideAA in vs.lua and it indeed seems to have fixed the problem
